FROM maven:3.9-eclipse-temurin-21

USER root

RUN apt-get update \
    && apt-get install -y docker.io git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN java -version && mvn -version

USER root